import React, { useState } from 'react';
import { Sparkles, FileText, UploadCloud, CheckCircle2, AlertCircle, X, ChevronRight, Package, Wrench, Truck, Info, Settings, ShieldCheck, DollarSign, Download, Building, Tag, MapPin, Hash, Mail, ArrowRight, Edit3, Check, Users, Shield, FileCheck, Lock, Plus } from 'lucide-react';
import { extractQuotationDetails, exportPRExcel, saveAiPr } from '../api/aiClient';

const AiQuotationParser = () => {
  const [file, setFile] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isConfirming, setIsConfirming] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [error, setError] = useState(null);
  const [parsedData, setParsedData] = useState(null);
  const [entryMode, setEntryMode] = useState('ai'); // 'ai' | 'manual'

  const handleManualEntry = () => {
    setEntryMode('manual');
    setParsedData({
      indentNo: '',
      department: metadata.department,
      date: metadata.date,
      main_item: { 
        description: 'Manual PR Entry', 
        specification: 'Self-declared items', 
        quantity: 1, 
        unit_price: 0, 
        total_price: 0, 
        reason: 'Manually entered PR',
        unit: 'SET'
      },
      items: [{ description: '', specification: '', uom: 'QTY', requirement: 1, value: 0 }],
      grand_total: 0
    });
    setIsEditing(true);
    setError(null);
  };

  const handleAddLineItem = () => {
    if (!parsedData) return;
    const newItems = [...parsedData.items, { description: '', specification: '', uom: 'QTY', requirement: 1, value: 0 }];
    setParsedData(prev => ({ ...prev, items: newItems }));
  };

  const handleMainItemUpdate = (field, value) => {
    setParsedData(prev => ({
        ...prev,
        main_item: { ...prev.main_item, [field]: value }
    }));
  };

  // Metadata fields with defaults
  const [metadata, setMetadata] = useState({
    indentNo: null, // Will be auto-generated by backend if not provided
    department: 'Mining',
    wbs: 'M-1017-M-MIN-PM',
    area: 'Plant Site',
    ros: 'Immediate',
    indentorEmail: '',
    approverS1: '',
    verifierS2: '',
    finalApproverS3: '',
    date: new Date().toISOString().split('T')[0]
  });

  const handleMetadataChange = (e) => {
    const { name, value } = e.target;
    setMetadata(prev => ({ ...prev, [name]: value }));
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
      setParsedData(null);
      setError(null);
      setSaveSuccess(false);
      setIsConfirming(false);
    }
  };

  const handleClear = () => {
    setFile(null);
    setParsedData(null);
    setError(null);
    setSaveSuccess(false);
    setIsConfirming(false);
    setEntryMode('ai');
    setIsEditing(false);
  };

  const handleAnalyze = async () => {
    if (!file) {
      setError("Please select a file first.");
      return;
    }

    setIsLoading(true);
    setError(null);
    setParsedData(null);
    setSaveSuccess(false);
    setIsConfirming(false);

    try {
      console.log("[AI Parser] Starting analysis for file:", file.name);
      console.log("[AI Parser] Metadata context:", metadata);

      // Send both file and user-provided metadata
      const result = await extractQuotationDetails(file, metadata);

      console.log("[AI Parser] Analysis complete. Raw extracted data:", result);
      setParsedData(result);

      // Seamlessly update metadata state with AI-extracted suggestions
      setMetadata(prev => ({
        ...prev,
        indentNo: result.indentNo || prev.indentNo,
        department: result.department || prev.department,
        area: result.area || prev.area,
        wbs: result.wbs || prev.wbs,
        date: result.date || prev.date
      }));
    } catch (err) {
      console.error("[AI Parser] Analysis failed:", err);
      setError(err.message || "An error occurred while analyzing the document.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleExport = async () => {
    if (!parsedData) return;
    setIsExporting(true);
    try {
      await exportPRExcel(parsedData, parsedData.indentNo);
    } catch (err) {
      setError("Failed to export Excel file.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleSaveClick = () => {
    if (!parsedData) return;
    setIsConfirming(true);
  };

  const handleFinalConfirm = async () => {
    setIsSaving(true);
    setError(null);
    try {
      console.log("[AI Parser] Initiating final PR save to tracking list...");

      // Final Recalculation before saving
      const total = (parsedData.items || []).reduce((acc, item) => acc + (Number(item.value) || 0), 0);
      const finalData = {
        ...parsedData,
        grand_total: total,
        department: metadata.department,
        indentNo: metadata.indentNo,
        area: metadata.area,
        ros: metadata.ros,
        wbs: metadata.wbs,
        date: metadata.date,
        indentorEmail: metadata.indentorEmail,
        approverS1: metadata.approverS1,
        verifierS2: metadata.verifierS2,
        finalApproverS3: metadata.finalApproverS3
      };

      console.log("[AI Parser] Saving final payload:", finalData);
      const savedPr = await saveAiPr(finalData);
      console.log("[AI Parser] PR Save Success. Server Response:", savedPr);

      setSaveSuccess(true);
      setIsConfirming(false);
    } catch (err) {
      console.error("[AI Parser] PR Save Error:", err);
      setError(err.message || "Failed to save PR to tracking list.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleItemUpdate = (index, field, value) => {
    if (!parsedData) return;
    const newItems = [...parsedData.items];
    newItems[index] = { ...newItems[index], [field]: value };

    // Auto-recalculate grand total in the JSON too
    const newTotal = newItems.reduce((acc, item) => acc + (Number(item.value) || 0), 0);

    setParsedData(prev => ({
      ...prev,
      items: newItems,
      grand_total: newTotal
    }));
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-20">
      <div className="flex items-center space-x-3 text-slate-800">
        <div className="p-2 bg-indigo-100 rounded-xl shadow-sm">
          <Sparkles className="text-indigo-600" size={24} />
        </div>
        <div>
          <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-violet-500">
            PR Intelligence Hub
          </h1>
          <p className="text-slate-500 text-sm font-medium">Auto-generate corporate PR templates from any quotation.</p>
        </div>
      </div>

      {/* Mode Selector */}
      {!parsedData && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-3xl">
           <button 
             onClick={() => setEntryMode('ai')}
             className={`flex items-center p-4 rounded-2xl border-2 transition-all text-left ${entryMode === 'ai' ? 'border-indigo-600 bg-indigo-50/50' : 'border-slate-100 bg-white hover:border-slate-200'}`}
           >
             <div className={`p-3 rounded-xl mr-4 ${entryMode === 'ai' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-400'}`}>
               <Sparkles size={24} />
             </div>
             <div>
               <p className="font-black text-slate-800">AI Quotation Upload</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Fill form automatically using AI</p>
             </div>
           </button>

           <button 
             onClick={handleManualEntry}
             className={`flex items-center p-4 rounded-2xl border-2 transition-all text-left ${entryMode === 'manual' ? 'border-indigo-600 bg-indigo-50/50' : 'border-slate-100 bg-white hover:border-slate-200'}`}
           >
             <div className={`p-3 rounded-xl mr-4 ${entryMode === 'manual' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-400'}`}>
               <Edit3 size={24} />
             </div>
             <div>
               <p className="font-black text-slate-800">Manual Entry</p>
               <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">Fill details manually without file</p>
             </div>
           </button>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Config & Upload Column */}
        <div className="lg:col-span-1 space-y-6">
          {/* Metadata Form */}
          <div className="bg-white border rounded-2xl shadow-sm p-5 space-y-4">
            <div className="flex items-center space-x-2 text-slate-400 mb-1 border-b pb-2">
              <Settings size={14} />
              <span className="text-[10px] uppercase font-bold tracking-wider">PR Configuration</span>
            </div>


            <InputField icon={<Building size={14} />} label="Dept" name="department" value={metadata.department} onChange={handleMetadataChange} required={true} />
            <InputField icon={<MapPin size={14} />} label="Area" name="area" value={metadata.area} onChange={handleMetadataChange} required={true} />
            <InputField icon={<AlertCircle size={14} />} label="Urgency (ROS)" name="ros" value={metadata.ros} onChange={handleMetadataChange} required={true} />

            <div className="pt-2 border-t mt-2 space-y-2">
              <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest block mb-2">Workflow Contacts</span>
              <InputField icon={<Users size={14} />} label="Indentor Email (Confirmation)" name="indentorEmail" value={metadata.indentorEmail} onChange={handleMetadataChange} placeholder="e.g. indentor@company.com" required={true} />
              <InputField icon={<Shield size={14} />} label="Stage 1: PR Approver" name="approverS1" value={metadata.approverS1} onChange={handleMetadataChange} placeholder="e.g. manager@company.com" required={true} />
              <InputField icon={<FileCheck size={14} />} label="Stage 2: Verifier" name="verifierS2" value={metadata.verifierS2} onChange={handleMetadataChange} placeholder="e.g. verifier@company.com" required={true} />
              <InputField icon={<Lock size={14} />} label="Stage 3: Final Approver" name="finalApproverS3" value={metadata.finalApproverS3} onChange={handleMetadataChange} placeholder="director@company.com" required={true} />
            </div>
          </div>

          {entryMode === 'ai' && (
            <div className="bg-white border rounded-2xl shadow-sm p-6 flex flex-col items-center justify-center text-center space-y-4">
              {!file ? (
              <label className="w-full flex flex-col items-center px-4 py-8 bg-slate-50 text-indigo rounded-xl tracking-wide uppercase border border-indigo-100 cursor-pointer hover:bg-white hover:border-indigo-300 border-dashed border-2 transition-all">
                <UploadCloud size={40} className="text-slate-300 mb-3" />
                <span className="text-sm font-bold text-slate-500 mb-1">Select Quotation</span>
                <span className="text-[10px] text-slate-400">PDF, JPG, PNG (Max 10MB)</span>
                <input type="file" className="hidden" accept="application/pdf,image/*" onChange={handleFileChange} />
              </label>
            ) : (
              <div className="w-full">
                <div className="flex items-center justify-between p-3 bg-indigo-50 rounded-xl border border-indigo-100">
                  <div className="flex items-center space-x-2 overflow-hidden">
                    <div className="p-1.5 bg-white rounded-lg shadow-sm flex-shrink-0">
                      <FileText className="text-indigo-500" size={16} />
                    </div>
                    <div className="flex flex-col text-left overflow-hidden">
                      <span className="text-xs font-bold text-slate-700 truncate">{file.name}</span>
                      <span className="text-[10px] text-slate-500 font-medium">{(file.size / 1024 / 1024).toFixed(2)} MB</span>
                    </div>
                  </div>
                  <button onClick={handleClear} className="p-1 hover:bg-white rounded-md transition-colors text-slate-400 hover:text-red-500">
                    <X size={14} />
                  </button>
                </div>

                <button
                  onClick={handleAnalyze}
                  disabled={isLoading}
                  className="w-full mt-4 flex items-center justify-center py-2.5 px-4 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 shadow-md shadow-indigo-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed text-xs"
                >
                  {isLoading ? (
                    <span className="flex items-center space-x-2">
                      <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      <span>Processing...</span>
                    </span>
                  ) : (
                    <span className="flex items-center space-x-2 uppercase tracking-wide">
                      <Sparkles size={16} />
                      <span>Prepare PR</span>
                    </span>
                  )}
                </button>
              </div>
            )}

            {error && (
              <div className="w-full flex items-start space-x-3 p-4 bg-red-50 text-red-700 rounded-2xl text-xs text-left border-2 border-red-100 shadow-sm animate-in shake duration-500">
                <div className="p-1.5 bg-red-100 rounded-lg flex-shrink-0">
                  <AlertCircle size={16} className="text-red-600" />
                </div>
                <div className="flex flex-col space-y-1">
                  <span className="font-black uppercase tracking-wider text-[10px]">Action Failed</span>
                  <span className="font-medium leading-relaxed">{error}</span>
                </div>
              </div>
            )}
          </div>
          )}
        </div>

        {/* Results Dashboard */}
        <div className="lg:col-span-3 space-y-6">
          {!parsedData ? (
            <div className="bg-white border rounded-3xl h-[450px] flex flex-col items-center justify-center text-slate-400 space-y-4">
              <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center border border-slate-100">
                <FileText size={24} className="text-slate-200" />
              </div>
              <div className="text-center">
                <p className="font-bold text-slate-500">No Document Data</p>
                <p className="text-[10px] max-w-[200px] mt-1 leadings-relaxed">Configure the Indent and Department then upload a quote to generate the PR draft.</p>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {/* PR Header & Actions */}
              <div className="bg-white border rounded-3xl p-6 shadow-sm flex flex-col lg:flex-row justify-between items-center gap-6">
                <div className="flex items-center space-x-4">
                  <div className={`p-3 rounded-2xl text-white shadow-lg transition-all ${saveSuccess ? 'bg-green-500 shadow-green-200' : 'bg-indigo-600 shadow-indigo-200'}`}>
                    {saveSuccess ? <CheckCircle2 size={20} /> : <FileText size={20} />}
                  </div>
                  <div>
                    <h2 className="text-xl font-black text-slate-800">Draft Indent: {parsedData.indentNo || 'Pending Allocation'}</h2>
                    <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                      {saveSuccess ? (
                        <span className="text-green-600 flex items-center gap-1">
                          <CheckCircle2 size={12} /> PR Saved and Tracked Successfully
                        </span>
                      ) : (
                        `${parsedData.department} • ${parsedData.date}`
                      )}
                    </p>
                  </div>
                </div>

                <div className="flex flex-wrap items-center justify-center gap-3">
                  <button
                    onClick={handleExport}
                    disabled={isExporting || isSaving}
                    className="flex items-center space-x-2 px-6 py-3 bg-white border border-slate-200 text-slate-600 rounded-2xl font-black text-sm hover:bg-slate-50 transition-all shadow-sm disabled:opacity-50"
                  >
                    {isExporting ? 'Exporting...' : (
                      <>
                        <Download size={18} />
                        <span>Download Excel</span>
                      </>
                    )}
                  </button>

                  <button
                    onClick={handleSaveClick}
                    disabled={isSaving || saveSuccess}
                    className={`flex items-center space-x-2 px-6 py-3 text-white rounded-2xl font-black text-sm transition-all shadow-lg disabled:opacity-50 ${saveSuccess ? 'bg-green-500 shadow-green-100 cursor-default' : 'bg-indigo-600 hover:bg-indigo-700 shadow-indigo-100'}`}
                  >
                    {isSaving ? (
                      <>
                        <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        <span>Saving...</span>
                      </>
                    ) : saveSuccess ? (
                      <>
                        <CheckCircle2 size={18} />
                        <span>Saved & Notified</span>
                      </>
                    ) : (
                      <>
                        <ShieldCheck size={18} />
                        <span>Verify & Save PR</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Strategic Analysis Section */}
              <div className="space-y-6">
                {/* Main Item Highlight */}
                <div className="relative overflow-hidden bg-white border border-indigo-100 rounded-3xl shadow-sm p-8">
                  <div className="absolute top-0 right-0 p-4">
                    <div className="px-3 py-1 bg-indigo-600 text-white text-[10px] font-black uppercase tracking-widest rounded-full shadow-lg shadow-indigo-100">
                      Primary Asset
                    </div>
                  </div>

                  <div className="flex flex-col md:flex-row items-start md:items-center gap-6">
                    <div className="flex-shrink-0 p-4 bg-indigo-50 rounded-2xl border border-indigo-100">
                      <Package size={48} className="text-indigo-600" />
                    </div>
                    <div className="flex-grow space-y-2">
                       <div className="flex items-center space-x-2">
                        {isEditing ? (
                          <div className="flex flex-col w-full gap-2">
                             <input 
                               className="text-xl font-bold text-slate-800 bg-white border border-slate-200 rounded-lg p-2 focus:ring-2 focus:ring-indigo-100 outline-none w-full"
                               value={parsedData.main_item?.description}
                               onChange={(e) => handleMainItemUpdate('description', e.target.value)}
                               placeholder="Main Item Description"
                             />
                             <textarea 
                               className="text-sm font-medium text-slate-500 bg-white border border-slate-200 rounded-lg p-2 focus:ring-2 focus:ring-indigo-100 outline-none w-full"
                               value={parsedData.main_item?.specification}
                               onChange={(e) => handleMainItemUpdate('specification', e.target.value)}
                               placeholder="Main Item Specifications"
                             />
                          </div>
                        ) : (
                          <>
                            <h2 className="text-2xl font-bold text-slate-800 leading-tight">
                              {parsedData.main_item?.description}
                            </h2>
                            <div className="p-1 px-2 bg-slate-100 rounded text-[10px] font-bold text-slate-500">
                              {parsedData.main_item?.unit}
                            </div>
                          </>
                        )}
                      </div>
                      {!isEditing && (
                         <p className="text-slate-500 text-sm leading-relaxed max-w-xl">
                           {parsedData.main_item?.specification}
                         </p>
                      )}
                      
                      <div className="pt-2 flex flex-wrap gap-4 text-xs font-bold text-slate-400">
                        <span className="flex items-center space-x-1">
                          <ChevronRight size={14} className="text-indigo-400" />
                          <span>QTY </span>
                          {isEditing ? (
                             <input 
                                type="number"
                                className="w-12 bg-white border border-slate-100 rounded text-[10px] p-1"
                                value={parsedData.main_item?.quantity}
                                onChange={(e) => handleMainItemUpdate('quantity', Number(e.target.value))}
                             />
                          ) : parsedData.main_item?.quantity}
                        </span>
                        <span className="flex items-center space-x-1">
                          <ChevronRight size={14} className="text-indigo-400" />
                          <span>UNIT PRICE: $</span>
                          {isEditing ? (
                             <input 
                                type="number"
                                className="w-20 bg-white border border-slate-100 rounded text-[10px] p-1"
                                value={parsedData.main_item?.unit_price}
                                onChange={(e) => handleMainItemUpdate('unit_price', Number(e.target.value))}
                             />
                          ) : parsedData.main_item?.unit_price?.toLocaleString()}
                        </span>
                      </div>
                    </div>
                    <div className="flex-shrink-0 text-right bg-slate-50 p-6 rounded-2xl border border-slate-100 w-full md:w-auto">
                      <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Quotation Value</div>
                      <div className="text-3xl font-black text-indigo-700">${parsedData.grand_total?.toLocaleString()}</div>
                      <div className="text-[10px] font-medium text-slate-400 mt-1 italic">Asset: ${parsedData.main_item?.total_price?.toLocaleString()}</div>
                    </div>
                  </div>

                  <div className="mt-8 p-4 bg-indigo-50/50 rounded-xl border border-indigo-100/50 flex items-start space-x-3">
                    <ShieldCheck className="text-indigo-600 flex-shrink-0 mt-0.5" size={18} />
                    <div className="text-xs text-indigo-900 leading-relaxed italic">
                      <span className="font-bold uppercase tracking-tighter not-italic mr-2 px-1.5 py-0.5 bg-indigo-100 rounded text-[9px]">AI Reasoning</span>
                      "{parsedData.main_item?.reason}"
                    </div>
                  </div>
                </div>


              </div>

              {/* Items Table */}
              <div className="bg-white border rounded-3xl shadow-sm overflow-hidden">
                <div className="p-5 border-b bg-slate-50 flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <Package className="text-slate-700" size={18} />
                    <h3 className="font-bold text-slate-700">Cost Breakdown</h3>
                  </div>
                  <div className="flex items-center space-x-3">
                    <button
                      onClick={() => setIsEditing(!isEditing)}
                      className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase transition-all border ${isEditing ? 'bg-indigo-600 text-white border-indigo-500 shadow-lg shadow-indigo-100' : 'bg-white text-slate-500 border-slate-200 hover:bg-slate-50'}`}
                    >
                      {isEditing ? (
                        <>
                          <Check size={12} />
                          <span>Close Edit Mode</span>
                        </>
                      ) : (
                        <>
                          <Edit3 size={12} />
                          <span>Enable Manual Edits</span>
                        </>
                      )}
                    </button>
                    <span className="text-[10px] font-bold text-slate-400 bg-slate-200/50 px-2 py-0.5 rounded-full uppercase">
                      {parsedData.items?.length || 0} Total
                    </span>
                  </div>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-50 text-slate-500 font-bold border-b">
                      <tr>
                        <th className="px-6 py-4">#</th>
                        <th className="px-6 py-4">DESCRIPTION & SPEC</th>
                        <th className="px-6 py-4">UOM</th>
                        <th className="px-6 py-4 text-center">QTY</th>
                        <th className="px-6 py-4 text-right">EST. VALUE</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y relative">
                      {parsedData.items?.map((item, idx) => (
                        <tr key={idx} className={`hover:bg-slate-50/50 transition-colors ${isEditing ? 'bg-indigo-50/10' : ''}`}>
                          <td className="px-6 py-4 text-slate-400 font-bold">{idx + 1}</td>
                          <td className="px-6 py-4 max-w-sm">
                            {isEditing ? (
                              <textarea
                                className="w-full bg-white border border-slate-200 rounded-lg p-2 text-xs font-bold text-slate-800 focus:ring-2 focus:ring-indigo-100 outline-none"
                                value={item.description}
                                onChange={(e) => handleItemUpdate(idx, 'description', e.target.value)}
                              />
                            ) : (
                              <>
                                <div className="font-bold text-slate-800">{item.description}</div>
                                <div className="text-[10px] text-slate-500 mt-0.5">{item.specification} • {item.size}</div>
                              </>
                            )}
                          </td>
                          <td className="px-6 py-4 text-slate-600 font-medium">
                            {isEditing ? (
                              <input
                                className="w-16 bg-white border border-slate-200 rounded-lg p-2 text-xs font-bold focus:ring-2 focus:ring-indigo-100 outline-none"
                                value={item.uom}
                                onChange={(e) => handleItemUpdate(idx, 'uom', e.target.value)}
                              />
                            ) : item.uom}
                          </td>
                          <td className="px-6 py-4 text-center font-bold text-slate-800">
                            {isEditing ? (
                              <input
                                className="w-20 text-center bg-white border border-slate-200 rounded-lg p-2 text-xs font-black focus:ring-2 focus:ring-indigo-100 outline-none"
                                value={item.requirement}
                                onChange={(e) => handleItemUpdate(idx, 'requirement', e.target.value)}
                              />
                            ) : item.requirement}
                          </td>
                          <td className="px-6 py-4 text-right font-black text-indigo-600">
                            {isEditing ? (
                              <div className="flex justify-end items-center space-x-1">
                                <span className="text-slate-400">$</span>
                                <input
                                  type="number"
                                  className="w-24 text-right bg-white border border-slate-200 rounded-lg p-2 text-xs font-black text-indigo-700 focus:ring-2 focus:ring-indigo-100 outline-none"
                                  value={item.value}
                                  onChange={(e) => handleItemUpdate(idx, 'value', Number(e.target.value))}
                                />
                              </div>
                            ) : (
                              `$${Number(item.value)?.toLocaleString()}`
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot className="bg-indigo-50/30 border-t-2 border-indigo-100">
                      <tr>
                        <td colSpan="2" className="px-6 py-4">
                           {isEditing && (
                              <button 
                                onClick={handleAddLineItem}
                                className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-xl text-[10px] font-black uppercase shadow-lg shadow-indigo-100 hover:bg-indigo-700 transition-all active:scale-95"
                              >
                                <Plus size={14} />
                                <span>Add New Item Row</span>
                              </button>
                           )}
                        </td>
                        <td colSpan="2" className="px-6 py-4 text-right font-bold text-slate-500 uppercase tracking-wider">
                          Grand Total (Sum of Items)
                        </td>
                        <td className="px-6 py-4 text-right font-black text-indigo-700 text-sm">
                          ${parsedData.items?.reduce((acc, item) => acc + (Number(item.value) || 0), 0)?.toLocaleString()}
                        </td>
                      </tr>
                    </tfoot>
                    <tbody className="divide-y">

                    </tbody>

                  </table>
                </div>
              </div>

              {/* Metadata Summary */}
              <div className="bg-slate-50 border rounded-3xl p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center space-x-2">
                    <Tag size={12} />
                    <span>Distribution Info</span>
                  </h4>
                  <div className="space-y-2">
                    <DetailRow label="Department" value={metadata.department} />
                    <DetailRow label="Area of Use" value={metadata.area} />
                    <DetailRow label="Urgency (ROS)" value={metadata.ros} />
                    <DetailRow label="Nominated Approver" value={metadata.approverS1 || 'Not Specified'} />
                    <DetailRow label="Date Produced" value={metadata.date} />
                  </div>
                </div>
                <div className="space-y-4 border-l md:pl-6">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center space-x-2">
                    <Settings size={12} />
                    <span>Account Coding</span>
                  </h4>
                  <div className="space-y-2">
                    <DetailRow label="WBS Code" value={isEditing ? "(Hidden)" : "Calculated Post-Approval"} />
                    <DetailRow label="PR Status" value="DRAFT" />
                    <DetailRow label="Urgency (ROS)" value={metadata.ros} />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Confirmation Overlay (Original PR Summary) */}
      {isConfirming && parsedData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-md animate-in fade-in duration-300" onClick={() => setIsConfirming(false)} />
          <div className="relative bg-white w-full max-w-lg rounded-[32px] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200 border border-slate-200">
            {/* Modal Header */}
            <div className="bg-slate-50 px-8 py-6 border-b border-slate-100 flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-indigo-200">
                  <ShieldCheck size={20} />
                </div>
                <div>
                  <h3 className="font-black text-slate-800 tracking-tight">Final PR Verification</h3>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Original PR Draft Review</p>
                </div>
              </div>
              <button onClick={() => setIsConfirming(false)} className="text-slate-400 hover:text-slate-600 transition-colors">
                <X size={20} />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-8 space-y-6">
              <div className="space-y-4">
                <div className="flex items-start space-x-3 p-4 bg-indigo-50/50 rounded-2xl border border-indigo-100/50">
                  <Mail className="text-indigo-600 mt-0.5" size={18} />
                  <div>
                    <p className="text-[10px] text-slate-500 font-medium leading-relaxed mt-0.5">
                      Sequential workflow will notify in order:
                      <span className="block font-black text-indigo-700 mt-1">
                        1. Indentor: {metadata.indentorEmail || '(Not Selected)'} (Confirmation)<br />
                        2. Stage 1: {metadata.approverS1 || '(Not Selected)'} (PR Approver)<br />
                        3. Stage 2: {metadata.verifierS2 || '(Not Selected)'} (Verifier)<br />
                        4. Stage 3: {metadata.finalApproverS3 || '(Not Selected)'} (Final Approver)
                      </span>
                    </p>
                  </div>
                </div>

                <div className="bg-white border-2 border-slate-100 rounded-2xl overflow-hidden">
                  <div className="px-5 py-3 bg-slate-50 border-b border-slate-100 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                    Verification Details
                  </div>
                  <div className="p-5 space-y-3">
                    <div className="flex justify-between items-center text-xs">
                      <span className="text-slate-400 font-bold uppercase tracking-wider">Department</span>
                      <span className="text-slate-800 font-black">{metadata.department}</span>
                    </div>
                    <div className="flex justify-between items-center text-xs">
                      <span className="text-slate-400 font-bold uppercase tracking-wider">Main Asset</span>
                      <span className="text-slate-800 font-black line-clamp-1">{parsedData.main_item?.description}</span>
                    </div>
                    <div className="pt-3 border-t-2 border-slate-50 flex justify-between items-center group">
                      <span className="text-slate-500 font-black uppercase tracking-wider text-xs">Grand Total</span>
                      <span className="text-indigo-600 font-black text-xl tracking-tight group-hover:scale-105 transition-transform">
                        ${parsedData.items?.reduce((acc, item) => acc + (item.value || 0), 0)?.toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-3 pt-2">
                <button
                  onClick={() => setIsConfirming(false)}
                  className="flex-1 py-4 px-6 bg-slate-50 text-slate-500 rounded-2xl font-black text-sm hover:bg-slate-100 transition-all active:scale-95"
                >
                  Edit PR
                </button>
                <button
                  onClick={handleFinalConfirm}
                  disabled={isSaving}
                  className="flex-[2] py-4 px-6 bg-indigo-600 text-white rounded-2xl font-black text-sm shadow-xl shadow-indigo-200 hover:bg-indigo-700 transition-all flex items-center justify-center space-x-2 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? (
                    <div className="flex items-center space-x-2">
                      <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      <span>Processing...</span>
                    </div>
                  ) : (
                    <>
                      <span>Confirm & Notify</span>
                      <ArrowRight size={18} />
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const InputField = ({ icon, label, name, value, onChange, placeholder, disabled, required = false }) => (
  <div className="space-y-1.5">
    <label className="text-[10px] font-bold text-slate-400 uppercase ml-1">
      {label} {required && <span className="text-red-400">*</span>}
    </label>
    <div className={`relative group ${disabled ? 'opacity-60' : ''}`}>
      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400 group-focus-within:text-indigo-500 transition-colors">
        {icon}
      </div>
      <input
        type="text"
        name={name}
        value={value}
        onChange={onChange}
        disabled={disabled}
        required={required}
        placeholder={placeholder}
        className="block w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-100 rounded-xl text-xs font-semibold focus:bg-white focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50/50 outline-none transition-all placeholder:text-slate-300"
      />
    </div>
  </div>
);

const DetailRow = ({ label, value }) => (
  <div className="flex justify-between items-center bg-white/50 p-2 rounded-lg border border-white/80">
    <span className="text-[10px] font-medium text-slate-500">{label}</span>
    <span className="text-xs font-bold text-slate-700">{value}</span>
  </div>
);

export default AiQuotationParser;
